using Leihbuecherrei_GFS.GUI;

namespace Leihbuecherrei_GFS
{
    public partial class LibraryWindow : Form
    {
        private Control control;

        public LibraryWindow( Control pControl )
        {
            control = pControl;
            InitializeComponent();

            //bind the Readers list to the Listbox LbReaders. only has to be done once
            showReaderList();
        }

        private void BtnAddBook_Click( object sender, EventArgs e )
        {
            AddBookWindow addBookWindow = new AddBookWindow();

            addBookWindow.Location = new Point(0, 0);
            addBookWindow.Show();
        }

        private void BtnAddReader_Click( object sender, EventArgs e )
        {
            AddReaderWindow addReaderWindow = new AddReaderWindow(control);

            addReaderWindow.Location = new Point(0, 0);
            addReaderWindow.Show();
        }

        public void showReaderList()
        {
            LbReaders.DataSource = null;
            LbReaders.DataSource = control.GetReaders();

            //sets what atribute is shown in the ListBox. DisplayMember wont accept custom Getter thats why i have to use the autogenerated sytax for getter ans setter
            LbReaders.DisplayMember = "idAndName";
        }

        private void LbReaders_DoubleClick( object sender, EventArgs e )
        {
            Reader selectedReader = LbReaders.SelectedItem as Reader;

            DisplayReadersWindow displayReaders = new DisplayReadersWindow(control, selectedReader);

            displayReaders.Location = new Point(0, 0);
            displayReaders.Show();
        }
    }
}